### ISSUE TITLE
Route Middleware 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by eggplantiny** [JungKyuHyun/guest-book#1]
안녕하세요. 프로젝트를 관심있게 살펴보던 중 궁금한게 생겨서 질문드립니다.

[여기](https://github.com/JungKyuHyun/guest-book/blob/2903becf5500a95fc1dc11472a50acd6c56a40d9/server/src/index.ts#L22)처럼 Route 를 초기화 해주는 방법을 사용하면 

전역 Middleware 가 아닌 각 Route 마다 Middleware 를 지정해 줄 경우 어떻게 구현할 수 있을까요?

예를들어 로그인한 사용자만 접근할 수 있는 글쓰기 API인 `POST /api/article` 를 작성한다면

`isSigninUser` 라는 미들웨어를 작성해서 코드 중복을 피할 수 있을건데

현재 구현되어있는 인터페이스라면 적용이 조금 어려워 보일것 같다는 생각이 들었습니다.

감사합니다.

**Comment by JungKyuHyun** [comment]
안녕하세요,
아직 서버쪽은 수정전이긴 했는데, 해당 부분은 확인하여 선 반영했습니다 :) 
의견 정말 감사드립니다.
